language: python
python:
  - "3.6"   


stages:
  - name: test

jobs:
  include:
    - stage: test
      name: Unit Tests
     script: 
       - python manage.py makemigrations
         python manage.py migrate
         python manage.py test api

install:
  - pip install -r requirements.txt

script: pytest


