language: python
python:
  - "3.6"   


stages:
  - name: migrate
  - name: test

jobs:
  include:
    - stage: migrate
      name: Migration
      script: python manage.py makemigrations
      script: python manage.py migrate

    - stage: test
      name: Unit Tests
      script: python manage.py test

install:
  - pip install -r requirements.txt

script: pytest


